version : '3.7'
services:
  backend:
    image: backend
    build:
      args:
        - target=dev
    environment:
      ENV: dev
      PORT: 6100
      DB_HOST: mongodb
      DB_PORT: 27017
    volumes:
      - .:/app
    ports:
      - "6100:6100"
    expose:
      - "6100"
    depends_on:
      - mongodb
    networks:
      - articode_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /home/ubun2/mongodb/data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - articode_network

networks:
  articode_network: